### ISSUE TITLE
What’s the Extended Source Code?

### ISSUE THREAD

**Issue by sclausen** [Matthew-J-Spencer/Ultimate-2D-Controller#11]
Hi there! I would really appreciate the info what to expect for the paid "Extenden Source Code"

Thank you very much for this and everything you do on YouTube!

**Comment by Matthew-J-Spencer** [comment]
I converted it to standard unity physics, making it much easier to use and incorporate into your game. 
It's even smoother to play than the current version. 
Fixed a bunch of bugs.
Added dash and double jump (more planned).

And of course better support.

**Comment by ThomasACampbell** [comment]
Can you show a little bit of the extended code? I'd like to know what it's like before I "buy" it.

**Comment by Matthew-J-Spencer** [comment]
You can play the output of the extended controller here: https://tarodev.itch.io/extended-ultimate-2d-controller

It's a bit outdated as it has additional features now, but it gives you a good idea of the upgrade.

**Comment by crackingtutsyt** [comment]
can I get that on the $3.50 patreon? or $8 only
