### ISSUE TITLE
Deeply nested loops on collision detection

### ISSUE THREAD

**Issue by kwhitejr** [Matthew-J-Spencer/Ultimate-2D-Controller#13]
Right off the top wanted to say thanks for open sourcing this. Been reading through the `PlayerController` and learning a lot. I'll also concede that I spend most of my time with Javascript and Java, so not sure if the following concern plays out in C#.

It seems like there are some deeply nested iterations involved with collision detection and I'm wondering if dramatically impacts performance if, for example, you had multiple players on screen at once?

Loop layers
1. [Calculate collisions](https://github.com/Matthew-J-Spencer/Ultimate-2D-Controller/blob/main/Scripts/PlayerController.cs#L93-L95)
```
_colUp = RunDetection(_raysUp);
_colLeft = RunDetection(_raysLeft);
_colRight = RunDetection(_raysRight);
```
Not an actual loop, but practically speaking occurs each `Update()`

2. [ Run Detection](https://github.com/Matthew-J-Spencer/Ultimate-2D-Controller/blob/main/Scripts/PlayerController.cs#L97)
```
EvaluateRayPositions(range).Any(point => Physics2D.Raycast(point, range.Dir, _detectionRayLength, _groundLayer));
```
Iterates over each point returned from `EvaluateRayPositions`

3.[ EvaluateRayPositions](https://github.com/Matthew-J-Spencer/Ultimate-2D-Controller/blob/main/Scripts/PlayerController.cs#L113)
```
for (var i = 0; i < _detectorCount; i++)
{
  var t = (float)i / (_detectorCount - 1);
  yield return Vector2.Lerp(range.Start, range.End, t);
}
```
Iterates over `_detectorCount`, which is defaulted to `3` but looks toggleable.

Minimum n^3 complexity per `Update`() and potentially n^4 if, for example, you additionally called `OnDrawGizmos()` within `Update()` (thank you for the Gizmo function, btw).

All that said, being new to both C# and Unity I'm not chock full of refactor ideas. I assume most of these layers are necessary. Could you execute the `RunDetection()` calls in parallel with something like `Parallel.ForEach`? Something analogous to Javscript's `Promise.all([foo(), bar()])`.

Anyway, great work!

**Comment by Matthew-J-Spencer** [comment]
All valid feedback. The controller source is now entirely different from the time of this post, but I appreciate your input :)
