### ISSUE TITLE
Ground Layer

### ISSUE THREAD

**Issue by ewillett2024** [Matthew-J-Spencer/Ultimate-2D-Controller#19]
I don't understand how to set the ground layer. The character moves just fine (seemingly), but I keep falling through the ground instantly. I have the ground placed and I made a layer titled _groundLayer but it doesn't work. I apologize if I'm just being an idiot and the fix is blatantly obvious, I'm a new developer and this is my first time trying to make a game.

And no I don't have the money to buy the patreon for the better code, and I'm not a skilled enough coder to convert the code in the free version to use rigidbodies.

**Comment by TitanStormer** [comment]
I have the very same problem.....

**Comment by Matthew-J-Spencer** [comment]
I've updated the free source with a far superior version. The problem mentioned here has been fixed.
