### ISSUE TITLE
Fall through ground on spawn

### ISSUE THREAD

**Issue by KoenRijpstra** [Matthew-J-Spencer/Ultimate-2D-Controller#2]
First of all thanks for all your hard work! 👏   

I got an issue that if the player spawn too close to the ground the player falls through. 

PS: Can i use this in a project?

**Comment by Matthew-J-Spencer** [comment]
You can use it, yes :)

I'll have a look into the falling through ground. Leaving open for now.

**Comment by KoenRijpstra** [comment]
Thanks! What kind of license?

**Comment by Matthew-J-Spencer** [comment]
MIT, so you can go and use it however you'd like. But if you release a production game maybe give me a small attribution :)

Bug fixed by the way. Very dirty but until I work out a better way it'll do.
