### ISSUE TITLE
Low FPS causes player to phase through colliders

### ISSUE THREAD

**Issue by UndefinedPotato** [Matthew-J-Spencer/Ultimate-2D-Controller#5]
Low FPS behavior can be tested by setting the target framerate.

```
private void Awake()
{
  Application.targetFrameRate = 10;
}
```

**Comment by Matthew-J-Spencer** [comment]
I've been working on this today. I think I'll be changing the controller to be frame-dependent, similar to celeste. 

A demo of the current frame-dependent version is here: https://tarodev.itch.io/ultimate-2d-controller-frame-dependent?secret=g7nlMP0Q4Duderm4UVuUUymOWnM

It works, but has a few bugs. Anyway, keeping open until solved.

**Comment by jcpenneykiosk** [comment]
Thanks for the information, I will try to figure it out for more.

**Comment by Matthew-J-Spencer** [comment]
A fair amount of work was involved and I've moved development of the project to [Patreon](https://www.patreon.com/tarodev)
