### ISSUE TITLE
character stuck in the corner after a jump, cannot be unstuck

### ISSUE THREAD

**Issue by Mohamed-Anes** [Matthew-J-Spencer/Ultimate-2D-Controller#6]
![Screenshot 2022-01-15 230611](https://user-images.githubusercontent.com/89668631/149639211-5545ddbd-f966-459e-b825-b7656adbd59a.png)

**Comment by Matthew-J-Spencer** [comment]
A fair bit was required to truly fix this bug. I've continued development on my [https://www.patreon.com/tarodev](Patreon)
