### ISSUE TITLE
leave the map when you jump from large height

### ISSUE THREAD

**Issue by Simerca** [Matthew-J-Spencer/Ultimate-2D-Controller#7]
Hi, thank you for this great job.
Can leave the map when you jump from large height;
Maybe Rigidbody Collision settings.

<img width="1023" alt="Capture d’écran 2022-01-17 à 11 26 57" src="https://user-images.githubusercontent.com/51412510/149752796-a4ec6d39-8735-4947-a43f-1daad17bbedd.png">

**Comment by Tymski** [comment]
This is caused by the lack of interpolation.

**Comment by Matthew-J-Spencer** [comment]
I've moved active development to my [https://www.patreon.com/tarodev](Patreon).
