### ISSUE TITLE
Character stuck in mid air

### ISSUE THREAD

**Issue by Tymski** [Matthew-J-Spencer/Ultimate-2D-Controller#8]
I got stuck here without the ability to move anywhere, can't jump. On inputs left/right the character just slightly tilts.
![image](https://user-images.githubusercontent.com/8183632/149807486-62568ce0-76a0-4f14-9823-eccd165e18ec.png)

**Comment by Matthew-J-Spencer** [comment]
I've converted the controller to use standard Unity physics. Although I won't be updating this version any longer. I have an extended version in active development on my [https://www.patreon.com/tarodev](Patreon)
